version: '3'

services:
  nodejs:
    image: 'node:18'
    container_name: builder-nodejs
    restart: always
    user: 1000:1000
    volumes:
      - ./:/home/app
    working_dir: /home/app
    network_mode: 'host'
    command: bash -c "tail -f /dev/null"
